message: Greetings from the command-api microservice [using the LOCALHOST config].

#debug: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true
    
spring:
    data:
        mongodb:
            uri: mongodb://mongodb:27017/products
logging:
    level:
        root: INFO
        org.springframework: DEBUG 
            #aop: DEBUG
            #dao: DEBUG
            #orm: DEBUG
            #amqp: DEBUG
            #data: DEBUG
            #transaction: DEBUG
        org.axonframework: INFO
        com.soagrowers: INFO
    file: ./build/logs/command-api.log
