message: Greetings from the gateway-spring microservice [using the container id config].

#debug: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true

spring:
  application:
    name: gateway-service-spring
  cloud.gateway:
    discovery:
      locator:
        enabled: true
        lowerCaseServiceId: true
    routes:
    - id: users
      uri: lb://command-api
      predicates:
        - Path=/user/**

logging:
    level:
        root: INFO
        org.springframework: INFO 
        org.axonframework: INFO
        com.soagrowers: INFO
    file: ./build/logs/gateway-service-spring.log
