message: Greetings from the gateway-spring microservice [using the container id config].

#debug: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true

spring:
  application:
    name: gateway-service-spring
  cloud.gateway:
    discovery:
      locator:
        enabled: true
        lowerCaseServiceId: true
    routes:
    - id: onboarding-service
      uri: lb://onboarding-service
      predicates:
        - Path=/onboarding-service/**
      filters:
#         - name: RequestRateLimiter
#           args:
#             key-resolver: '#{@userKeyResolver}'
#             redis-rate-limiter.replenishRate: 2
#             redis-rate-limiter.burstCapacity: 2
        - name: Hystrix
          args:
            name: neighborhoodsFallbackCommand
            fallbackUri: forward:/fallback/neighborhoods
        
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

logging:
    level:
        root: INFO
        org.springframework: INFO 
        org.axonframework: INFO
        com.soagrowers: INFO
    file: ./build/logs/gateway-service-spring.log
